import type { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  await knex.schema.raw(`
    CREATE TABLE users (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      login VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      password VARCHAR(255) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`);
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.raw('drop table users');
}
