@host = localhost:3000

###
# @name findAll
# @description Find all users
GET http://{{host}}/api/users

###
# @name createUser
# @description Create a new user
POST http://{{host}}/api/users
content-type: application/json

{
  "login": "test",
  "password": "test12345",
  "email": "test@test.com"
}
